name: tradenote
services:
  tradenote:
    image: eleventrading/tradenote
    container_name: tradenote_app
    expose:
      - 8080
    environment:
      MONGO_URI: mongodb://tradenote:tradenote@mongo:27017/tradenote?authSource=admin
      TRADENOTE_DATABASE: tradenote
      APP_ID: d921f112e189d49920da37f5f1367aad0d0fea7846bd4b0f
      MASTER_KEY: 34c5ac565f39293b66337134c8d9e4f99cff105eae256cbd
      TRADENOTE_PORT: 8080
    networks:
      - tradenote_net
  mongo:
    image: mongo:latest
    container_name: tradenote_db
    volumes:
      - tradenote_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tradenote
      MONGO_INITDB_ROOT_PASSWORD: tradenote
      MONGO_INITDB_DATABASE: tradenote
    networks:
      - tradenote_net
networks:
  tradenote_net:
    driver: bridge

volumes:
  tradenote_db:
    name: tradenote_db
